// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyseWord(arg1) {
  return window['go']['aianalyse']['Agent']['AnalyseWord'](arg1);
}
