// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWords(arg1, arg2) {
  return window['go']['words']['WordList']['GetWords'](arg1, arg2);
}

export function GetWordsArray() {
  return window['go']['words']['WordList']['GetWordsArray']();
}

export function GetWordsDiscription(arg1) {
  return window['go']['words']['WordList']['GetWordsDiscription'](arg1);
}
