// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {words} from '../models';

export function GetWords(arg1:words.Database,arg2:string):Promise<void>;

export function GetWordsArray():Promise<Array<words.Word>>;

export function GetWordsDiscription(arg1:words.Database):Promise<void>;
